### ISSUE TITLE
Need the code for unit telegram bot

### ISSUE THREAD

**Issue by NidukaAkalanka** [dopaemon/x-ui#51]
This isn't an issue though. Posting as the discussions are turned off. 
Can someone please tell me the way or the code for the unit of the telegram bot? Is it /web/service/telegram.go? 

Thanks and Rgards,
Niduka A 🤍

**Comment by dopaemon** [comment]
> This isn't an issue though. Posting as the discussions are turned off. Can someone please tell me the way or the code for the unit of the telegram bot? Is it /web/service/telegram.go?
> 
> Thanks and Rgards, Niduka A white_heart

yes this file.

**Comment by NidukaAkalanka** [comment]
Thanks a lot!
