### ISSUE TITLE
Bác fix hộ em cái này vs ạ

### ISSUE THREAD

**Issue by quydang04** [dopaemon/x-ui#54]
À bác ơi, em có sử dụng cái x-ui của bác á sao e chuyển cái x-ray version cứ chuyển là nó bị lỗi à bác với em cũng thử khởi động lại nhiều lần rồi nhưng vẫn bị, bác kiểm tra xem rồi fix lại được không ạ. Em cám ơn bác nhiều ạ.

**Comment by dopaemon** [comment]
dùng cái này bác: https://github.com/X-UI-Unofficial đi bâc

**Comment by quydang04** [comment]
> dùng cái này bác: https://github.com/X-UI-Unofficial đi bâc
Vậy em cám ơn bác nhiều ạ.

**Comment by dopaemon** [comment]
> > dùng cái này bác: https://github.com/X-UI-Unofficial đi bâc
> > Vậy em cám ơn bác nhiều ạ.

haha có gì đâu bro. https://t.me/X_UI_Unofficial nha
